### ISSUE TITLE
Seitenabstand von Beiträgen auch ohne Widget unter dem Menü

### ISSUE THREAD

**Issue by larsboehnke** [pfadfinden/wordpress-theme-updater#1]
Als Nutzer erwarte ich, dass meine Beiträge immer den selben Seitenabstand zu linken Seitenrand haben, auch wenn ich kein Widget unter dem Seitenmenü aktiviert habe das bis zur Höhe des Beginns der Beiträge reicht.
![bildschirmfoto 2015-08-02 um 16 11 38](https://cloud.githubusercontent.com/assets/11321756/9026491/3af5ddf0-3931-11e5-8c09-090c1d90cd23.png)
![bildschirmfoto 2015-08-02 um 16 10 44](https://cloud.githubusercontent.com/assets/11321756/9026492/3b187964-3931-11e5-8490-5854e3fc57a9.png)
![Uploading Bildschirmfoto 2015-08-02 um 16.10.16.png…]()

**Comment by corphi** [comment]
Weil sich Inhalte sich dynamisch ausrichten, geht das leider nicht einfach. Die Inhalte rutschen beiseite, wenn die Leiste lang genug ist.
Als Workaround tun es:
- Flachere/Abgeschaltete Bilder (siehe auch #2)
- Mehr Menüeinträge
- Mehr Widgets
- Blanko-Widget (Text; Inhalt `<div style="height:100px"></div>`)

**Comment by corphi** [comment]
Korrigiert in 0.99.6.
