### ISSUE TITLE
Menüpunkt Kategorie nicht aktiv bei Seitenbesuch

### ISSUE THREAD

**Issue by larsboehnke** [pfadfinden/wordpress-theme-updater#12]
Wenn ich einen Menüpunkt öffne, der eine Kategorieseite öffnet, ist der Menüpunkt im Menü nicht aktiv.
![bildschirmfoto 2015-09-19 um 19 12 22](https://cloud.githubusercontent.com/assets/11321756/9977316/7c5e35de-5f02-11e5-8004-d1c751745003.png)

**Comment by corphi** [comment]
Korrigiert in 0.99.6.
