### ISSUE TITLE
Verzerrte Bilder in der mobilen Version

### ISSUE THREAD

**Issue by julian-weide** [pfadfinden/wordpress-theme-updater#16]
Ich habe, um was auszuprobieren, heute mal unsere Stammeshomepage www.konadstein.de mit dem Handy aufgerufen. Dabei ist mir aufgefallen, dass sämtliche Titelbilder verzerrt sind. Könnte einer von euch mal schauen, ob das bei euch auch so ist (ein Bug?!) oder nur auf meinem schon etwas älteren Smartphone auftritt? Mein Umfeld hier ist leider nicht so Smartphoneafin, sonst würde ich auch einfach in der WG fragen... 

Nebenbei: Wie kann ich labels hinzufügen?

**Comment by larsboehnke** [comment]
Hallo @julian-weide, bei mir (iPhone 5s, iOS9, Safari) sieht alles normal aus. Es handelt sich also wohl um einen Anzeigebug deines mobilen Browsers. Welches Handy, OS und welchen Browser nutzt du denn?

Ich weiß gar nicht, ob du Labels hinzufügen kannst, ansonsten funktioniert dass rechts in der Leiste.

**Comment by julian-weide** [comment]
Mein Handy hat sich vor kurzem zerlegt und ich habe noch kein Update draufgezogen, also uralt-Android. Daher auch meine Vermutung, dass es am Handy liegt. Das ist dann wohl hiermit bestätigt, danke! 
Das Feld für Labels sehe ich, da kann ich aber nichts anklicken oder so. Das hat sich damit dann also auch geklärt.
