### ISSUE TITLE
Design nach Update kaputt

### ISSUE THREAD

**Issue by julian-weide** [pfadfinden/wordpress-theme-updater#20]
Hallo Leute, 

ein befreundeter Stamm hat mich um Hilfe gebeten. Nach einem Update des Designs war selbiges im Eimer. 
http://stamm-chatten.de/wp/
Da ich gerne bastle, aber weder wirklich Ahnung, noch Zugriff auf deren Wordpress habe, dachte ich, frage ich hier mal nach. 
Habt ihr ne Idee, was passiert sein könnte? Bzw. klar, Fehler beim Update, aber hat ihr einen Tipp für den Stamm, wie sie das ohne größeren Aufwand wieder beibiegen können? 

Danke und liebe Grüße
Julian

**Comment by cowboyxup** [comment]
nach dem update muss dass hautpmenü unter Design-->Anpassen-->Menüs->Hauptmenü wieder neu zugeordnet werden.

**Comment by julian-weide** [comment]
@cowboyxup Danke, das werde ich direkt so weitergeben.

**Comment by julian-weide** [comment]
Hallo Leute, 
ich habe heute die Verantwortliche des Stammes getroffen und das Zuweisen des Hauptmenüs hat funktioniert. Allerdings bleibt ein Fehler bestehen. Die Schriftart ist nicht die Richtige. Habt ihr Ideen, woran das liegen könnte? 
http://stamm-chatten.de/wp/
Danke noch mal und liebe Grüße
Julian
