### ISSUE TITLE
Schrift in der Newskachel ist blau

### ISSUE THREAD

**Issue by larsboehnke** [pfadfinden/wordpress-theme-updater#7]
Als Nutzer erwarte ich, dass Fließtext schwarz dargestellt wird.

http://lars-boehnke.de/wordpress/2015/08/10/zweiter-newsartikel/

**Comment by corphi** [comment]
Dann solltest du nur gültiges HTML in deine Widgets eintragen und das letzte `<a>` schließen.
Für reine Linklisten empfiehlt sich ohnehin ein Widget für eine Menüleiste.
