### ISSUE TITLE
Mobil sehe ich neben der Hauptkachel eine Kachel daneben angeschnitten

### ISSUE THREAD

**Issue by larsboehnke** [pfadfinden/wordpress-theme-updater#8]
Als Nutzer erwarte ich, dass ich eine Kachel in der vollen Breite sehe.
![img_2310](https://cloud.githubusercontent.com/assets/11321756/9184395/57de712c-3fb5-11e5-970b-43419e282a68.PNG)

**Comment by corphi** [comment]
So schmal kann ich den Firefox nicht machen… Aber eigentlich schaltet er schon bei 720px auf einspaltige Ansicht um.

**Comment by corphi** [comment]
Das ist ein bekannter Fehler in Safari bzw. Webkit:
- [Fehlerbeschreibung](https://github.com/philipwalton/flexbugs#11-min-and-max-size-declarations-are-ignored-when-wrapping-flex-items)
- [Bug im Webkit-Bugzilla](https://bugs.webkit.org/show_bug.cgi?id=136041)

**Comment by corphi** [comment]
Korrigiert in 0.99.7.
