### ISSUE TITLE
Hamburger Symbol ist in der mobilen Version etwas gequetscht

### ISSUE THREAD

**Issue by larsboehnke** [pfadfinden/wordpress-theme-updater#9]
Das Hamburger Menü könnte etwas mehr Space zwischen Wort-Bildmarke und Symbol brauchen.
![img_2310](https://cloud.githubusercontent.com/assets/11321756/9184414/74fbe7c6-3fb5-11e5-8e26-3770c7f19b92.PNG)

**Comment by corphi** [comment]
Wird in pfadfinden/buena-theme#1 weiter behandelt.
